;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        delete-indentation
        electric-newline-and-maybe-indent
        eval-last-sexp
        kill-region
        ))

(setq mc/cmds-to-run-once
      '(
        find-file
        next-buffer
        suspend-frame
        ))
